sudo: required

language: go

services:
  - docker

env:
  - SPEC_PATH="../schema/seed.manifest.schema.json" TESTDATA_PATH="../testdata/" TEMPLATES_PATH="../templates" ZIP="../testdata/seed-scale.zip" MOUNTAIN="../templates" HELLO="Hello World"

before_install:
  - if [[ "${TRAVIS_TAG}x" == "x" ]] ; then ./set-version.sh $(tail -1 .versions)-snapshot; ./spec/examples/inject-manifests.sh; fi
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor
  - ./validator/test-images/docker-build-test-images.sh

install:
  - git clone --depth=50 --branch=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/$TRAVIS_REPO_SLUG.git /home/travis/gopath/src/github.com/ngageoint/seed
  - go get github.com/xeipuuv/gojsonschema

script:
  - ./spec/add-version-links.sh
  - docker run -v $TRAVIS_BUILD_DIR/spec:/documents --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output index.adoc seed.adoc
  - docker run -v $TRAVIS_BUILD_DIR/spec:/documents --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output seed.adoc
  - go test -v ./...

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

before_deploy:
  - ./spec/collect-versioned-docs.sh

deploy:
  # Deployment that pushes GitHub releases of compiled spec docs associated with tag
  - provider: releases
    api_key: "$GH_TOKEN"
    file_glob: true
    file: spec/output/${TRAVIS_TAG}/*
    skip_cleanup: true
    on:
      tags: true

  # Only performed on master builds. For releases, timing of master build must be after artifacts are available.
  - provider: pages
    local_dir: spec/output
    skip_cleanup: true
    github_token: $GH_TOKEN
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST == false

