sudo: required

services:
  - docker

env:
  - SPEC_PATH="../schema/seed.manifest.schema.json"
  - SEED_VERSION=0.0.5

before_install:
  - ./set-version.sh ${SEED_VERSION}
  - ./examples/inject-manifests.sh
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor
  - ./validator/test-images/docker-build-test-images.sh

install:
  - go get github.com/xeipuuv/gojsonschema

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output *.adoc
  - go test -v ./...

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:
  - ./push-docs.sh
